#!/usr/bin/env python3
"""Publish a candidate Specialist's AUDIT.md and viability verdict into authoring/audits/.

Usage:
  publish_specialist_audit.py ID=viable | ID=not-viable:<failing gate> [...]

Reads F:/openscience-specialists/specialist-src/<ID>/AUDIT.md (override with OASS_SPECIALIST_SRC), writes
authoring/audits/<ID>/{AUDIT.md,verdict.json}, then regenerates authoring/audits/INDEX.md.
Moved from the factory's tools/publish_audits.py on 2026-09-21.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
AUDITS = os.path.join(HERE, "audits")
SPECIALIST_SRC = os.environ.get("OASS_SPECIALIST_SRC", "F:/openscience-specialists/specialist-src")


def write_text(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def publish(spec):
    specialist_id, _, verdict_text = spec.partition("=")
    verdict, _, gate = verdict_text.partition(":")
    if verdict not in ("viable", "not-viable"):
        raise SystemExit(f"{spec}: verdict must be viable or not-viable[:gate]")
    target = os.path.join(AUDITS, specialist_id)
    os.makedirs(target, exist_ok=True)
    with open(os.path.join(SPECIALIST_SRC, specialist_id, "AUDIT.md"), encoding="utf-8") as f:
        text = f.read().replace("\r\n", "\n")
    write_text(os.path.join(target, "AUDIT.md"), text)
    match = re.search(r"\b(20\d\d-\d\d-\d\d)\b", text)
    write_text(os.path.join(target, "verdict.json"), json.dumps({
        "specialist_id": specialist_id,
        "verdict": verdict.replace("-", " "),
        "failing_gate": gate or None,
        "recorded_on": match.group(1) if match else None,
    }, indent=2) + "\n")


def cell(value):
    return re.sub(r"\s+", " ", str(value if value is not None else "")).replace("|", "\\|").strip() or "—"


def regenerate_index():
    lines = ["# Specialist audit index", "",
             "Generated by `publish_specialist_audit.py`; do not edit by hand.", "",
             "| Specialist | Verdict | Failing gate | Recorded | Record |",
             "| --- | --- | --- | --- | --- |"]
    for specialist_id in sorted(os.listdir(AUDITS)):
        path = os.path.join(AUDITS, specialist_id, "verdict.json")
        if not os.path.isfile(path):
            continue
        with open(path, encoding="utf-8") as f:
            v = json.load(f)
        lines.append(f"| `{specialist_id}` | {cell(v['verdict'])} | {cell(v.get('failing_gate'))} | "
                     f"{cell(v.get('recorded_on'))} | [AUDIT.md]({specialist_id}/AUDIT.md) |")
    write_text(os.path.join(AUDITS, "INDEX.md"), "\n".join(lines) + "\n")


if __name__ == "__main__":
    for arg in sys.argv[1:]:
        publish(arg)
        print(f"published {arg}")
    regenerate_index()
